### ISSUE TITLE
lazygit config bug

### ISSUE THREAD

**Issue by a1liz** [m7medVision/lazycommit#6]
Hello, I found that the version v1.3.14 output just like
![image](https://github.com/user-attachments/assets/36e72ca0-c65e-4305-a196-a259440cdb9b)

But in latest version, the output is changed to:
![image](https://github.com/user-attachments/assets/9f0eef17-8123-4672-b584-55976c581de9)

It looks like that the lazygit config should be fixed to parse the json format.

**Comment by m7medVision** [comment]
Hi Mr. [a1liz](https://github.com/a1liz), I know this problem, and I gonna fix it at the nearest chance. If you want to contribute and fix it, you are welcome. It is related to templates

**Comment by a1liz** [comment]
Hello m7medVision, I try to fixed the output with
 `bunx @m7medvision/lazycommit@latest | sed -n '/^```json$/,/^```$/p' | sed '1d;$d' | jq -r '.commitMessages[]' | nl -s'. ' -w1 -nln`. 

It works in the CLI, but lazygit cannot parse it correctly yet.

**Comment by m7medVision** [comment]
I changed the template. Remove the old template from `~/.lazycommit-template`, and LazyGit should work well with the new release.

```yaml
customCommands:
  - key: "<c-a>" # ctrl + a
    description: "Pick AI commit"
    command: |
      echo "{{.Form.Msg}}" > .git/COMMIT_EDITMSG && \
      nvim .git/COMMIT_EDITMSG && \
      [ -s .git/COMMIT_EDITMSG ] && \
      git commit -F .git/COMMIT_EDITMSG || \
      echo "Commit message is empty, commit aborted."
    context: "files"
    subprocess: true
    prompts:
      - type: "menuFromCommand"
        title: "AI Commits"
        key: "Msg"
        command: "bunx @m7medvision/lazycommit@latest"
        filter: '^(?P<number>\d+)\.\s(?P<message>.+)$'
        valueFormat: "{{ .message }}"
        labelFormat: "{{ .number }}: {{ .message | green }}"

```
